"""Initial migration

Revision ID: 91460bf4141f
Revises: 
Create Date: 2024-05-30 07:07:07.045333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91460bf4141f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chartdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprocket_production_actual', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sprocket_production_goal', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('time', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initialdataload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loaded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprocket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teeth', sa.Integer(), nullable=False),
    sa.Column('pitch_diameter', sa.Float(), nullable=False),
    sa.Column('outside_diameter', sa.Float(), nullable=False),
    sa.Column('pitch', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chart_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chart_data_id'], ['chartdata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factory')
    op.drop_table('sprocket')
    op.drop_table('initialdataload')
    op.drop_table('chartdata')
    # ### end Alembic commands ###
