"""Initial migration

Revision ID: da249e45cd3e
Revises: 
Create Date: 2024-05-31 03:20:56.058555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'da249e45cd3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chartdata',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initialdataload',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loaded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factory',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chart_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chart_data_id'], ['chartdata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprocketproduction',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprocket_production_actual', sa.Integer(), nullable=False),
    sa.Column('sprocket_production_goal', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('chart_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chart_data_id'], ['chartdata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprockettype',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teeth', sa.Integer(), nullable=False),
    sa.Column('pitch_diameter', sa.Float(), nullable=False),
    sa.Column('outside_diameter', sa.Float(), nullable=False),
    sa.Column('pitch', sa.Float(), nullable=False),
    sa.Column('production_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['production_id'], ['sprocketproduction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sprockettype')
    op.drop_table('sprocketproduction')
    op.drop_table('factory')
    op.drop_table('initialdataload')
    op.drop_table('chartdata')
    # ### end Alembic commands ###
